In [9]:
from tensorflow import keras
from keras.layers import Dense, Input
from keras.activations import sigmoid
from keras import Sequential
from keras.losses import BinaryCrossentropy, MeanSquaredError
import numpy as np


In [4]:
linear_layer = keras.layers.Dense(units=1, activation='linear')

In [8]:
linear_layer.weights

[]

In [16]:
X_train = np.array([[5],[7]])


In [17]:
linear_layer(X_train[0].reshape(1, 1))

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[-2.726812]], dtype=float32)>

In [25]:
linear_layer.set_weights([np.array([[200]]), np.array([100])])
linear_layer.get_weights()

[array([[200.]], dtype=float32), array([100.], dtype=float32)]

In [26]:
linear_layer(np.array([[5]]))

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[1100.]], dtype=float32)>

In [30]:
X_train = np.array([0., 1, 2, 3, 4, 5], dtype=np.float32).reshape(-1,1)  # 2-D Matrix
Y_train = np.array([0,  0, 0, 1, 1, 1], dtype=np.float32).reshape(-1,1)  # 2-D Matrix

In [31]:
Y_train

array([[0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.]], dtype=float32)

In [32]:
model = Sequential(
    [
        keras.layers.Dense(1, input_dim=1,  activation = 'sigmoid', name='L1')
    ]
)

In [48]:
logistic_layer = model.get_layer('L1')

In [56]:
logistic_layer(np.array([[-1]]))

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[0.76469237]], dtype=float32)>

In [57]:
set_w = np.array([[2]])
set_b = np.array([-4.5])
logistic_layer.set_weights([set_w, set_b])

In [61]:
logistic_layer.get_weights()

[array([[2.]], dtype=float32), array([-4.5], dtype=float32)]

In [62]:
logistic_layer(np.array([[5]]))

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[0.99592984]], dtype=float32)>